### PR TITLE
Fix actions injection vulnerability

### PR DESCRIPTION
**Pull request by AdnaneKhan**
Using an environment variable to sanitize the issue title fixes the injection vulnerability. I've also updated the workflow only to grant issue read permission to the workflow as an added security measure (should only use the least privileges necessary to accomplish the task).

### CODE REVIEW

**Comment by sadsfae** [comment]
Thanks for the pull request.  We do not accept pull requests directly and instead use Gerrit code review as the vehicle for proposed changes.

https://github.com/redhat-performance/quads/blob/master/CONTRIBUTING.md#setup-github--gerrit-account-one-time-only

I think this _fix_ / _vulnerability_ is also not very realistic.  The `sed` actions we use only affect the title of issues that appear in webhook messages and is done completely on the Github side.  Someone would have to first comprise Github Actions subsystems to do anything and that anything is limited to the contents displayed in a webhook message anyway.

Furthermore this PR just seems to set an environment variable, but we're already using the GHA variable of `github.event.issue.title` so setting this to `$ISSUE_TITLE` doesn't appear to do anything beyond what we're doing anyway besides adding more abstraction than I can see.

**Comment by AdnaneKhan** [comment]
@sadsfae This vulnerability exists because of how GitHub Actions works under the hood. The `GITHUB_TOKEN` (added to each workflow run automatically) is what an attacker would target.  All of this is known publicly (see https://cycode.com/blog/github-actions-vulnerabilities/). 

As it stands now anyone can use this injection to push code to the master branch as well as modify the releases posted on this repository with a backdoor.

**Comment by sadsfae** [comment]
@AdnaneKhan go for it.

**Comment by sadsfae** [comment]
@AdnaneKhan  I stand corrected, thanks for your help with this.  Since we don't use PR I'm pushing a patch to Gerrit and will give you accreditation for the help and reporting.

**Pull request closed without merging**
